
<Structures>
  <Structure Name="unnamed structure" AutoFill="0" AutoCreate="1" DefaultHex="0" AutoDestroy="0" DoNotSaveLocal="0" RLECompression="1" AutoCreateStructsize="4096">
    <Elements>
      <Element Offset="0" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000000" DisplayMethod="unsigned integer"/>
      <Element Offset="16" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000010" DisplayMethod="unsigned integer"/>
      <Element Offset="24" Vartype="Pointer" Bytesize="8" OffsetHex="00000018" Description="下一個item" DisplayMethod="unsigned integer">
        <Structure Name="Autocreated from 26BCBDD90F8" AutoFill="0" AutoCreate="1" DefaultHex="0" AutoDestroy="0" DoNotSaveLocal="0" RLECompression="1" AutoCreateStructsize="4096">
          <Elements>
            <Element Offset="0" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000000" DisplayMethod="unsigned integer"/>
            <Element Offset="16" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000010" DisplayMethod="unsigned integer"/>
            <Element Offset="28" Vartype="Float" Bytesize="4" OffsetHex="0000001C" DisplayMethod="unsigned integer"/>
            <Element Offset="32" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000020" DisplayMethod="unsigned integer"/>
            <Element Offset="48" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000030" DisplayMethod="hexadecimal"/>
            <Element Offset="52" Vartype="String" Bytesize="4" OffsetHex="00000034" DisplayMethod="unsigned integer"/>
            <Element Offset="56" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000038" DisplayMethod="unsigned integer"/>
            <Element Offset="72" Vartype="Unicode String" Bytesize="16" OffsetHex="00000048" DisplayMethod="unsigned integer"/>
            <Element Offset="88" Vartype="Unicode String" Bytesize="8" OffsetHex="00000058" DisplayMethod="unsigned integer"/>
            <Element Offset="96" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000060" DisplayMethod="hexadecimal"/>
            <Element Offset="100" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000064" DisplayMethod="unsigned integer"/>
            <Element Offset="104" Vartype="String" Bytesize="86" OffsetHex="00000068" DisplayMethod="unsigned integer"/>
            <Element Offset="190" Vartype="Byte" Bytesize="1" RLECount="2" OffsetHex="000000BE" DisplayMethod="unsigned integer"/>
            <Element Offset="192" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="000000C0" DisplayMethod="unsigned integer"/>
            <Element Offset="204" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="000000CC" DisplayMethod="hexadecimal"/>
            <Element Offset="216" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000000D8" DisplayMethod="unsigned integer"/>
            <Element Offset="224" Vartype="Byte" Bytesize="1" RLECount="4" OffsetHex="000000E0" DisplayMethod="unsigned integer"/>
            <Element Offset="228" Vartype="4 Bytes" Bytesize="4" OffsetHex="000000E4" DisplayMethod="hexadecimal"/>
            <Element Offset="232" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="000000E8" DisplayMethod="unsigned integer"/>
            <Element Offset="256" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000100" DisplayMethod="unsigned integer"/>
            <Element Offset="272" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="00000110" DisplayMethod="unsigned integer"/>
            <Element Offset="296" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000128" DisplayMethod="unsigned integer"/>
            <Element Offset="312" Vartype="4 Bytes" Bytesize="4" RLECount="12" OffsetHex="00000138" DisplayMethod="unsigned integer"/>
            <Element Offset="360" Vartype="Pointer" Bytesize="8" RLECount="3" OffsetHex="00000168" DisplayMethod="unsigned integer"/>
            <Element Offset="384" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000180" DisplayMethod="unsigned integer"/>
            <Element Offset="392" Vartype="Pointer" Bytesize="8" OffsetHex="00000188" DisplayMethod="unsigned integer"/>
            <Element Offset="400" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000190" DisplayMethod="unsigned integer"/>
            <Element Offset="416" Vartype="String" Bytesize="4" OffsetHex="000001A0" DisplayMethod="unsigned integer"/>
            <Element Offset="420" Vartype="4 Bytes" Bytesize="4" OffsetHex="000001A4" DisplayMethod="hexadecimal"/>
            <Element Offset="424" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="000001A8" DisplayMethod="unsigned integer"/>
            <Element Offset="464" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000001D0" DisplayMethod="hexadecimal"/>
            <Element Offset="472" Vartype="4 Bytes" Bytesize="4" OffsetHex="000001D8" DisplayMethod="unsigned integer"/>
            <Element Offset="476" Vartype="4 Bytes" Bytesize="4" OffsetHex="000001DC" DisplayMethod="hexadecimal"/>
            <Element Offset="480" Vartype="4 Bytes" Bytesize="4" OffsetHex="000001E0" DisplayMethod="unsigned integer"/>
            <Element Offset="484" Vartype="4 Bytes" Bytesize="4" OffsetHex="000001E4" DisplayMethod="hexadecimal"/>
            <Element Offset="488" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="000001E8" DisplayMethod="unsigned integer"/>
            <Element Offset="504" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000001F8" DisplayMethod="unsigned integer"/>
            <Element Offset="512" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000200" DisplayMethod="unsigned integer"/>
            <Element Offset="528" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000210" DisplayMethod="unsigned integer"/>
            <Element Offset="536" Vartype="Double" Bytesize="8" OffsetHex="00000218" DisplayMethod="unsigned integer"/>
            <Element Offset="544" Vartype="4 Bytes" Bytesize="4" RLECount="5" OffsetHex="00000220" DisplayMethod="unsigned integer"/>
            <Element Offset="564" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000234" DisplayMethod="hexadecimal"/>
            <Element Offset="568" Vartype="Pointer" Bytesize="8" OffsetHex="00000238" DisplayMethod="unsigned integer"/>
            <Element Offset="576" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000240" DisplayMethod="unsigned integer"/>
            <Element Offset="584" Vartype="Unicode String" Bytesize="16" OffsetHex="00000248" DisplayMethod="unsigned integer"/>
            <Element Offset="600" Vartype="Unicode String" Bytesize="8" OffsetHex="00000258" DisplayMethod="unsigned integer"/>
            <Element Offset="608" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000260" DisplayMethod="hexadecimal"/>
            <Element Offset="612" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000264" DisplayMethod="unsigned integer"/>
            <Element Offset="616" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000268" DisplayMethod="hexadecimal"/>
            <Element Offset="620" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="0000026C" DisplayMethod="unsigned integer"/>
            <Element Offset="632" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000278" DisplayMethod="hexadecimal"/>
            <Element Offset="640" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000280" DisplayMethod="unsigned integer"/>
            <Element Offset="652" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="0000028C" DisplayMethod="hexadecimal"/>
            <Element Offset="668" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="0000029C" DisplayMethod="unsigned integer"/>
            <Element Offset="680" Vartype="4 Bytes" Bytesize="4" OffsetHex="000002A8" DisplayMethod="hexadecimal"/>
            <Element Offset="684" Vartype="Float" Bytesize="4" OffsetHex="000002AC" DisplayMethod="unsigned integer"/>
            <Element Offset="688" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="000002B0" DisplayMethod="unsigned integer"/>
            <Element Offset="700" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000002BC" DisplayMethod="hexadecimal"/>
            <Element Offset="708" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="000002C4" DisplayMethod="unsigned integer"/>
            <Element Offset="720" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000002D0" DisplayMethod="hexadecimal"/>
            <Element Offset="728" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000002D8" DisplayMethod="unsigned integer"/>
            <Element Offset="736" Vartype="Byte" Bytesize="1" RLECount="4" OffsetHex="000002E0" DisplayMethod="unsigned integer"/>
            <Element Offset="740" Vartype="4 Bytes" Bytesize="4" OffsetHex="000002E4" DisplayMethod="hexadecimal"/>
            <Element Offset="744" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="000002E8" DisplayMethod="unsigned integer"/>
            <Element Offset="768" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000300" DisplayMethod="unsigned integer"/>
            <Element Offset="784" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="00000310" DisplayMethod="unsigned integer"/>
            <Element Offset="808" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000328" DisplayMethod="unsigned integer"/>
            <Element Offset="824" Vartype="4 Bytes" Bytesize="4" RLECount="12" OffsetHex="00000338" DisplayMethod="unsigned integer"/>
            <Element Offset="872" Vartype="Pointer" Bytesize="8" RLECount="3" OffsetHex="00000368" DisplayMethod="unsigned integer"/>
            <Element Offset="896" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000380" DisplayMethod="unsigned integer"/>
            <Element Offset="904" Vartype="Pointer" Bytesize="8" OffsetHex="00000388" DisplayMethod="unsigned integer"/>
            <Element Offset="912" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000390" DisplayMethod="unsigned integer"/>
            <Element Offset="928" Vartype="String" Bytesize="4" OffsetHex="000003A0" DisplayMethod="unsigned integer"/>
            <Element Offset="932" Vartype="4 Bytes" Bytesize="4" OffsetHex="000003A4" DisplayMethod="hexadecimal"/>
            <Element Offset="936" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="000003A8" DisplayMethod="unsigned integer"/>
            <Element Offset="976" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000003D0" DisplayMethod="hexadecimal"/>
            <Element Offset="984" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="000003D8" DisplayMethod="unsigned integer"/>
            <Element Offset="996" Vartype="4 Bytes" Bytesize="4" OffsetHex="000003E4" DisplayMethod="hexadecimal"/>
            <Element Offset="1000" Vartype="Pointer" Bytesize="8" OffsetHex="000003E8" DisplayMethod="unsigned integer"/>
            <Element Offset="1008" Vartype="4 Bytes" Bytesize="4" RLECount="18" OffsetHex="000003F0" DisplayMethod="unsigned integer"/>
            <Element Offset="1080" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000438" DisplayMethod="unsigned integer"/>
            <Element Offset="1096" Vartype="4 Bytes" Bytesize="4" RLECount="16" OffsetHex="00000448" DisplayMethod="unsigned integer"/>
            <Element Offset="1160" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000488" DisplayMethod="unsigned integer"/>
            <Element Offset="1176" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000498" DisplayMethod="unsigned integer"/>
            <Element Offset="1184" Vartype="Pointer" Bytesize="8" RLECount="6" OffsetHex="000004A0" DisplayMethod="unsigned integer"/>
            <Element Offset="1232" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000004D0" DisplayMethod="hexadecimal"/>
            <Element Offset="1240" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="000004D8" DisplayMethod="unsigned integer"/>
            <Element Offset="1256" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000004E8" DisplayMethod="hexadecimal"/>
            <Element Offset="1264" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000004F0" DisplayMethod="unsigned integer"/>
            <Element Offset="1272" Vartype="Pointer" Bytesize="8" OffsetHex="000004F8" DisplayMethod="unsigned integer"/>
            <Element Offset="1280" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000500" DisplayMethod="unsigned integer"/>
            <Element Offset="1288" Vartype="Pointer" Bytesize="8" OffsetHex="00000508" DisplayMethod="unsigned integer"/>
            <Element Offset="1296" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000510" DisplayMethod="unsigned integer"/>
            <Element Offset="1300" Vartype="Double" Bytesize="8" OffsetHex="00000514" DisplayMethod="unsigned integer"/>
            <Element Offset="1308" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000051C" DisplayMethod="hexadecimal"/>
            <Element Offset="1312" Vartype="Pointer" Bytesize="8" OffsetHex="00000520" DisplayMethod="unsigned integer"/>
            <Element Offset="1320" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000528" DisplayMethod="unsigned integer"/>
            <Element Offset="1328" Vartype="Pointer" Bytesize="8" RLECount="3" OffsetHex="00000530" DisplayMethod="unsigned integer"/>
            <Element Offset="1352" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000548" DisplayMethod="unsigned integer"/>
            <Element Offset="1368" Vartype="Pointer" Bytesize="8" OffsetHex="00000558" DisplayMethod="unsigned integer"/>
            <Element Offset="1376" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000560" DisplayMethod="unsigned integer"/>
            <Element Offset="1384" Vartype="Pointer" Bytesize="8" OffsetHex="00000568" DisplayMethod="unsigned integer"/>
            <Element Offset="1392" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000570" DisplayMethod="unsigned integer"/>
            <Element Offset="1400" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000578" DisplayMethod="hexadecimal"/>
            <Element Offset="1404" Vartype="4 Bytes" Bytesize="4" RLECount="13" OffsetHex="0000057C" DisplayMethod="unsigned integer"/>
            <Element Offset="1456" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000005B0" DisplayMethod="hexadecimal"/>
            <Element Offset="1464" Vartype="Pointer" Bytesize="8" OffsetHex="000005B8" DisplayMethod="unsigned integer"/>
            <Element Offset="1472" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000005C0" DisplayMethod="unsigned integer"/>
            <Element Offset="1480" Vartype="String" Bytesize="7" OffsetHex="000005C8" DisplayMethod="unsigned integer"/>
            <Element Offset="1487" Vartype="Byte" Bytesize="1" OffsetHex="000005CF" DisplayMethod="unsigned integer"/>
            <Element Offset="1488" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000005D0" DisplayMethod="hexadecimal"/>
            <Element Offset="1496" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000005D8" DisplayMethod="unsigned integer"/>
            <Element Offset="1504" Vartype="Byte" Bytesize="1" RLECount="4" OffsetHex="000005E0" DisplayMethod="unsigned integer"/>
            <Element Offset="1508" Vartype="4 Bytes" Bytesize="4" OffsetHex="000005E4" DisplayMethod="hexadecimal"/>
            <Element Offset="1512" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="000005E8" DisplayMethod="unsigned integer"/>
            <Element Offset="1536" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000600" DisplayMethod="unsigned integer"/>
            <Element Offset="1552" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="00000610" DisplayMethod="unsigned integer"/>
            <Element Offset="1576" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000628" DisplayMethod="unsigned integer"/>
            <Element Offset="1592" Vartype="4 Bytes" Bytesize="4" RLECount="12" OffsetHex="00000638" DisplayMethod="unsigned integer"/>
            <Element Offset="1640" Vartype="Pointer" Bytesize="8" RLECount="3" OffsetHex="00000668" DisplayMethod="unsigned integer"/>
            <Element Offset="1664" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000680" DisplayMethod="unsigned integer"/>
            <Element Offset="1672" Vartype="Pointer" Bytesize="8" OffsetHex="00000688" DisplayMethod="unsigned integer"/>
            <Element Offset="1680" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000690" DisplayMethod="unsigned integer"/>
            <Element Offset="1696" Vartype="String" Bytesize="4" OffsetHex="000006A0" DisplayMethod="unsigned integer"/>
            <Element Offset="1700" Vartype="4 Bytes" Bytesize="4" OffsetHex="000006A4" DisplayMethod="hexadecimal"/>
            <Element Offset="1704" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="000006A8" DisplayMethod="unsigned integer"/>
            <Element Offset="1744" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000006D0" DisplayMethod="hexadecimal"/>
            <Element Offset="1752" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000006D8" DisplayMethod="unsigned integer"/>
            <Element Offset="1760" Vartype="Byte" Bytesize="1" RLECount="4" OffsetHex="000006E0" DisplayMethod="unsigned integer"/>
            <Element Offset="1764" Vartype="4 Bytes" Bytesize="4" OffsetHex="000006E4" DisplayMethod="hexadecimal"/>
            <Element Offset="1768" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="000006E8" DisplayMethod="unsigned integer"/>
            <Element Offset="1792" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000700" DisplayMethod="unsigned integer"/>
            <Element Offset="1808" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="00000710" DisplayMethod="unsigned integer"/>
            <Element Offset="1832" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000728" DisplayMethod="unsigned integer"/>
            <Element Offset="1848" Vartype="4 Bytes" Bytesize="4" RLECount="12" OffsetHex="00000738" DisplayMethod="unsigned integer"/>
            <Element Offset="1896" Vartype="Pointer" Bytesize="8" RLECount="3" OffsetHex="00000768" DisplayMethod="unsigned integer"/>
            <Element Offset="1920" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000780" DisplayMethod="unsigned integer"/>
            <Element Offset="1928" Vartype="Pointer" Bytesize="8" OffsetHex="00000788" DisplayMethod="unsigned integer"/>
            <Element Offset="1936" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000790" DisplayMethod="unsigned integer"/>
            <Element Offset="1952" Vartype="String" Bytesize="4" OffsetHex="000007A0" DisplayMethod="unsigned integer"/>
            <Element Offset="1956" Vartype="4 Bytes" Bytesize="4" OffsetHex="000007A4" DisplayMethod="hexadecimal"/>
            <Element Offset="1960" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="000007A8" DisplayMethod="unsigned integer"/>
            <Element Offset="2000" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000007D0" DisplayMethod="hexadecimal"/>
            <Element Offset="2008" Vartype="Pointer" Bytesize="8" OffsetHex="000007D8" DisplayMethod="unsigned integer"/>
            <Element Offset="2016" Vartype="4 Bytes" Bytesize="4" OffsetHex="000007E0" DisplayMethod="hexadecimal"/>
            <Element Offset="2020" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000007E4" DisplayMethod="unsigned integer"/>
            <Element Offset="2028" Vartype="4 Bytes" Bytesize="4" OffsetHex="000007EC" DisplayMethod="hexadecimal"/>
            <Element Offset="2032" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000007F0" DisplayMethod="unsigned integer"/>
            <Element Offset="2040" Vartype="Pointer" Bytesize="8" OffsetHex="000007F8" DisplayMethod="unsigned integer"/>
            <Element Offset="2048" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000800" DisplayMethod="hexadecimal"/>
            <Element Offset="2052" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000804" DisplayMethod="unsigned integer"/>
            <Element Offset="2060" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000080C" DisplayMethod="hexadecimal"/>
            <Element Offset="2064" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000810" DisplayMethod="unsigned integer"/>
            <Element Offset="2072" Vartype="Pointer" Bytesize="8" OffsetHex="00000818" DisplayMethod="unsigned integer"/>
            <Element Offset="2080" Vartype="4 Bytes" Bytesize="4" RLECount="12" OffsetHex="00000820" DisplayMethod="unsigned integer"/>
            <Element Offset="2128" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000850" DisplayMethod="hexadecimal"/>
            <Element Offset="2132" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000854" DisplayMethod="unsigned integer"/>
            <Element Offset="2140" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000085C" DisplayMethod="hexadecimal"/>
            <Element Offset="2144" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000860" DisplayMethod="unsigned integer"/>
            <Element Offset="2152" Vartype="Pointer" Bytesize="8" OffsetHex="00000868" DisplayMethod="unsigned integer"/>
            <Element Offset="2160" Vartype="Float" Bytesize="4" OffsetHex="00000870" DisplayMethod="unsigned integer"/>
            <Element Offset="2164" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000874" DisplayMethod="unsigned integer"/>
            <Element Offset="2172" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000087C" DisplayMethod="hexadecimal"/>
            <Element Offset="2176" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000880" DisplayMethod="unsigned integer"/>
            <Element Offset="2184" Vartype="Pointer" Bytesize="8" OffsetHex="00000888" DisplayMethod="unsigned integer"/>
            <Element Offset="2192" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000890" DisplayMethod="hexadecimal"/>
            <Element Offset="2196" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000894" DisplayMethod="unsigned integer"/>
            <Element Offset="2204" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000089C" DisplayMethod="hexadecimal"/>
            <Element Offset="2208" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000008A0" DisplayMethod="unsigned integer"/>
            <Element Offset="2216" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="000008A8" DisplayMethod="unsigned integer"/>
            <Element Offset="2232" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="000008B8" DisplayMethod="unsigned integer"/>
            <Element Offset="2256" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000008D0" DisplayMethod="hexadecimal"/>
            <Element Offset="2264" Vartype="Pointer" Bytesize="8" OffsetHex="000008D8" DisplayMethod="unsigned integer"/>
            <Element Offset="2272" Vartype="4 Bytes" Bytesize="4" OffsetHex="000008E0" DisplayMethod="hexadecimal"/>
            <Element Offset="2276" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000008E4" DisplayMethod="unsigned integer"/>
            <Element Offset="2284" Vartype="4 Bytes" Bytesize="4" OffsetHex="000008EC" DisplayMethod="hexadecimal"/>
            <Element Offset="2288" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000008F0" DisplayMethod="unsigned integer"/>
            <Element Offset="2296" Vartype="Pointer" Bytesize="8" OffsetHex="000008F8" DisplayMethod="unsigned integer"/>
            <Element Offset="2304" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000900" DisplayMethod="hexadecimal"/>
            <Element Offset="2308" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000904" DisplayMethod="unsigned integer"/>
            <Element Offset="2316" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000090C" DisplayMethod="hexadecimal"/>
            <Element Offset="2320" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000910" DisplayMethod="unsigned integer"/>
            <Element Offset="2328" Vartype="Pointer" Bytesize="8" OffsetHex="00000918" DisplayMethod="unsigned integer"/>
            <Element Offset="2336" Vartype="Float" Bytesize="4" OffsetHex="00000920" DisplayMethod="unsigned integer"/>
            <Element Offset="2340" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000924" DisplayMethod="unsigned integer"/>
            <Element Offset="2348" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000092C" DisplayMethod="hexadecimal"/>
            <Element Offset="2352" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000930" DisplayMethod="unsigned integer"/>
            <Element Offset="2360" Vartype="Pointer" Bytesize="8" OffsetHex="00000938" DisplayMethod="unsigned integer"/>
            <Element Offset="2368" Vartype="4 Bytes" Bytesize="4" RLECount="7" OffsetHex="00000940" DisplayMethod="unsigned integer"/>
            <Element Offset="2396" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000095C" DisplayMethod="hexadecimal"/>
            <Element Offset="2400" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000960" DisplayMethod="unsigned integer"/>
            <Element Offset="2408" Vartype="Pointer" Bytesize="8" OffsetHex="00000968" DisplayMethod="unsigned integer"/>
            <Element Offset="2416" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000970" DisplayMethod="hexadecimal"/>
            <Element Offset="2420" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000974" DisplayMethod="unsigned integer"/>
            <Element Offset="2428" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000097C" DisplayMethod="hexadecimal"/>
            <Element Offset="2432" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000980" DisplayMethod="unsigned integer"/>
            <Element Offset="2440" Vartype="Pointer" Bytesize="8" OffsetHex="00000988" DisplayMethod="unsigned integer"/>
            <Element Offset="2448" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000990" DisplayMethod="hexadecimal"/>
            <Element Offset="2452" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000994" DisplayMethod="unsigned integer"/>
            <Element Offset="2460" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000099C" DisplayMethod="hexadecimal"/>
            <Element Offset="2464" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000009A0" DisplayMethod="unsigned integer"/>
            <Element Offset="2472" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="000009A8" DisplayMethod="unsigned integer"/>
            <Element Offset="2488" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="000009B8" DisplayMethod="unsigned integer"/>
            <Element Offset="2512" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000009D0" DisplayMethod="hexadecimal"/>
            <Element Offset="2520" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000009D8" DisplayMethod="unsigned integer"/>
            <Element Offset="2528" Vartype="Byte" Bytesize="1" RLECount="4" OffsetHex="000009E0" DisplayMethod="unsigned integer"/>
            <Element Offset="2532" Vartype="4 Bytes" Bytesize="4" OffsetHex="000009E4" DisplayMethod="hexadecimal"/>
            <Element Offset="2536" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="000009E8" DisplayMethod="unsigned integer"/>
            <Element Offset="2560" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000A00" DisplayMethod="unsigned integer"/>
            <Element Offset="2576" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="00000A10" DisplayMethod="unsigned integer"/>
            <Element Offset="2600" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000A28" DisplayMethod="unsigned integer"/>
            <Element Offset="2616" Vartype="4 Bytes" Bytesize="4" RLECount="12" OffsetHex="00000A38" DisplayMethod="unsigned integer"/>
            <Element Offset="2664" Vartype="Pointer" Bytesize="8" RLECount="3" OffsetHex="00000A68" DisplayMethod="unsigned integer"/>
            <Element Offset="2688" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000A80" DisplayMethod="unsigned integer"/>
            <Element Offset="2696" Vartype="Pointer" Bytesize="8" OffsetHex="00000A88" DisplayMethod="unsigned integer"/>
            <Element Offset="2704" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000A90" DisplayMethod="unsigned integer"/>
            <Element Offset="2720" Vartype="String" Bytesize="4" OffsetHex="00000AA0" DisplayMethod="unsigned integer"/>
            <Element Offset="2724" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000AA4" DisplayMethod="hexadecimal"/>
            <Element Offset="2728" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="00000AA8" DisplayMethod="unsigned integer"/>
            <Element Offset="2768" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000AD0" DisplayMethod="hexadecimal"/>
            <Element Offset="2776" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000AD8" DisplayMethod="unsigned integer"/>
            <Element Offset="2788" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000AE4" DisplayMethod="hexadecimal"/>
            <Element Offset="2792" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000AE8" DisplayMethod="unsigned integer"/>
            <Element Offset="2808" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000AF8" DisplayMethod="unsigned integer"/>
            <Element Offset="2816" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000B00" DisplayMethod="unsigned integer"/>
            <Element Offset="2832" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000B10" DisplayMethod="unsigned integer"/>
            <Element Offset="2844" Vartype="Float" Bytesize="4" OffsetHex="00000B1C" DisplayMethod="unsigned integer"/>
            <Element Offset="2848" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="00000B20" DisplayMethod="unsigned integer"/>
            <Element Offset="2872" Vartype="Pointer" Bytesize="8" OffsetHex="00000B38" DisplayMethod="unsigned integer"/>
            <Element Offset="2880" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000B40" DisplayMethod="unsigned integer"/>
            <Element Offset="2888" Vartype="Unicode String" Bytesize="12" OffsetHex="00000B48" DisplayMethod="unsigned integer"/>
            <Element Offset="2900" Vartype="Unicode String" Bytesize="6" OffsetHex="00000B54" DisplayMethod="unsigned integer"/>
            <Element Offset="2906" Vartype="Byte" Bytesize="1" OffsetHex="00000B5A" DisplayMethod="unsigned integer"/>
            <Element Offset="2907" Vartype="2 Bytes" Bytesize="2" OffsetHex="00000B5B" DisplayMethod="unsigned integer"/>
            <Element Offset="2909" Vartype="Byte" Bytesize="1" RLECount="3" OffsetHex="00000B5D" DisplayMethod="unsigned integer"/>
            <Element Offset="2912" Vartype="4 Bytes" Bytesize="4" RLECount="28" OffsetHex="00000B60" DisplayMethod="unsigned integer"/>
            <Element Offset="3024" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000BD0" DisplayMethod="hexadecimal"/>
            <Element Offset="3032" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000BD8" DisplayMethod="unsigned integer"/>
            <Element Offset="3040" Vartype="Byte" Bytesize="1" RLECount="4" OffsetHex="00000BE0" DisplayMethod="unsigned integer"/>
            <Element Offset="3044" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000BE4" DisplayMethod="hexadecimal"/>
            <Element Offset="3048" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="00000BE8" DisplayMethod="unsigned integer"/>
            <Element Offset="3072" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000C00" DisplayMethod="unsigned integer"/>
            <Element Offset="3088" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="00000C10" DisplayMethod="unsigned integer"/>
            <Element Offset="3112" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000C28" DisplayMethod="unsigned integer"/>
            <Element Offset="3128" Vartype="4 Bytes" Bytesize="4" RLECount="12" OffsetHex="00000C38" DisplayMethod="unsigned integer"/>
            <Element Offset="3176" Vartype="Pointer" Bytesize="8" RLECount="3" OffsetHex="00000C68" DisplayMethod="unsigned integer"/>
            <Element Offset="3200" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000C80" DisplayMethod="unsigned integer"/>
            <Element Offset="3208" Vartype="Pointer" Bytesize="8" OffsetHex="00000C88" DisplayMethod="unsigned integer"/>
            <Element Offset="3216" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000C90" DisplayMethod="unsigned integer"/>
            <Element Offset="3232" Vartype="String" Bytesize="4" OffsetHex="00000CA0" DisplayMethod="unsigned integer"/>
            <Element Offset="3236" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000CA4" DisplayMethod="hexadecimal"/>
            <Element Offset="3240" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="00000CA8" DisplayMethod="unsigned integer"/>
            <Element Offset="3280" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000CD0" DisplayMethod="hexadecimal"/>
            <Element Offset="3288" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000CD8" DisplayMethod="unsigned integer"/>
            <Element Offset="3296" Vartype="Byte" Bytesize="1" RLECount="4" OffsetHex="00000CE0" DisplayMethod="unsigned integer"/>
            <Element Offset="3300" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000CE4" DisplayMethod="hexadecimal"/>
            <Element Offset="3304" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="00000CE8" DisplayMethod="unsigned integer"/>
            <Element Offset="3328" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000D00" DisplayMethod="unsigned integer"/>
            <Element Offset="3344" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="00000D10" DisplayMethod="unsigned integer"/>
            <Element Offset="3368" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000D28" DisplayMethod="unsigned integer"/>
            <Element Offset="3384" Vartype="4 Bytes" Bytesize="4" RLECount="12" OffsetHex="00000D38" DisplayMethod="unsigned integer"/>
            <Element Offset="3432" Vartype="Pointer" Bytesize="8" RLECount="3" OffsetHex="00000D68" DisplayMethod="unsigned integer"/>
            <Element Offset="3456" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000D80" DisplayMethod="unsigned integer"/>
            <Element Offset="3464" Vartype="Pointer" Bytesize="8" OffsetHex="00000D88" DisplayMethod="unsigned integer"/>
            <Element Offset="3472" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000D90" DisplayMethod="unsigned integer"/>
            <Element Offset="3488" Vartype="String" Bytesize="4" OffsetHex="00000DA0" DisplayMethod="unsigned integer"/>
            <Element Offset="3492" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000DA4" DisplayMethod="hexadecimal"/>
            <Element Offset="3496" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="00000DA8" DisplayMethod="unsigned integer"/>
            <Element Offset="3536" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000DD0" DisplayMethod="hexadecimal"/>
            <Element Offset="3544" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000DD8" DisplayMethod="unsigned integer"/>
            <Element Offset="3552" Vartype="Byte" Bytesize="1" RLECount="4" OffsetHex="00000DE0" DisplayMethod="unsigned integer"/>
            <Element Offset="3556" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000DE4" DisplayMethod="hexadecimal"/>
            <Element Offset="3560" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="00000DE8" DisplayMethod="unsigned integer"/>
            <Element Offset="3584" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000E00" DisplayMethod="unsigned integer"/>
            <Element Offset="3600" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="00000E10" DisplayMethod="unsigned integer"/>
            <Element Offset="3624" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000E28" DisplayMethod="unsigned integer"/>
            <Element Offset="3640" Vartype="4 Bytes" Bytesize="4" RLECount="12" OffsetHex="00000E38" DisplayMethod="unsigned integer"/>
            <Element Offset="3688" Vartype="Pointer" Bytesize="8" RLECount="3" OffsetHex="00000E68" DisplayMethod="unsigned integer"/>
            <Element Offset="3712" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000E80" DisplayMethod="unsigned integer"/>
            <Element Offset="3720" Vartype="Pointer" Bytesize="8" OffsetHex="00000E88" DisplayMethod="unsigned integer"/>
            <Element Offset="3728" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000E90" DisplayMethod="unsigned integer"/>
            <Element Offset="3744" Vartype="String" Bytesize="4" OffsetHex="00000EA0" DisplayMethod="unsigned integer"/>
            <Element Offset="3748" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000EA4" DisplayMethod="hexadecimal"/>
            <Element Offset="3752" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="00000EA8" DisplayMethod="unsigned integer"/>
            <Element Offset="3792" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000ED0" DisplayMethod="hexadecimal"/>
            <Element Offset="3800" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000ED8" DisplayMethod="unsigned integer"/>
            <Element Offset="3808" Vartype="Byte" Bytesize="1" RLECount="4" OffsetHex="00000EE0" DisplayMethod="unsigned integer"/>
            <Element Offset="3812" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000EE4" DisplayMethod="hexadecimal"/>
            <Element Offset="3816" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="00000EE8" DisplayMethod="unsigned integer"/>
            <Element Offset="3840" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000F00" DisplayMethod="unsigned integer"/>
            <Element Offset="3856" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="00000F10" DisplayMethod="unsigned integer"/>
            <Element Offset="3880" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000F28" DisplayMethod="unsigned integer"/>
            <Element Offset="3896" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000F38" DisplayMethod="unsigned integer"/>
            <Element Offset="3912" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000F48" DisplayMethod="hexadecimal"/>
            <Element Offset="3928" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000F58" DisplayMethod="unsigned integer"/>
            <Element Offset="3944" Vartype="Pointer" Bytesize="8" RLECount="3" OffsetHex="00000F68" DisplayMethod="unsigned integer"/>
            <Element Offset="3968" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000F80" DisplayMethod="unsigned integer"/>
            <Element Offset="3976" Vartype="Pointer" Bytesize="8" OffsetHex="00000F88" DisplayMethod="unsigned integer"/>
            <Element Offset="3984" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000F90" DisplayMethod="unsigned integer"/>
            <Element Offset="4000" Vartype="String" Bytesize="4" OffsetHex="00000FA0" DisplayMethod="unsigned integer"/>
            <Element Offset="4004" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000FA4" DisplayMethod="hexadecimal"/>
            <Element Offset="4008" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="00000FA8" DisplayMethod="unsigned integer"/>
            <Element Offset="4048" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000FD0" DisplayMethod="hexadecimal"/>
            <Element Offset="4056" Vartype="Pointer" Bytesize="8" RLECount="3" OffsetHex="00000FD8" DisplayMethod="unsigned integer"/>
            <Element Offset="4080" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000FF0" DisplayMethod="unsigned integer"/>
          </Elements>
        </Structure>
      </Element>
      <Element Offset="32" Vartype="Pointer" Bytesize="8" OffsetHex="00000020" DisplayMethod="unsigned integer"/>
      <Element Offset="40" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000028" DisplayMethod="unsigned integer"/>
      <Element Offset="48" Vartype="Float" Bytesize="4" OffsetHex="00000030" Description="x" DisplayMethod="unsigned integer"/>
      <Element Offset="52" Vartype="Float" Bytesize="4" OffsetHex="00000034" Description="y" DisplayMethod="unsigned integer"/>
      <Element Offset="56" Vartype="Float" Bytesize="4" OffsetHex="00000038" Description="z" DisplayMethod="unsigned integer"/>
      <Element Offset="60" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="0000003C" DisplayMethod="unsigned integer"/>
      <Element Offset="72" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000048" DisplayMethod="hexadecimal"/>
      <Element Offset="76" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000004C" DisplayMethod="unsigned integer"/>
      <Element Offset="80" Vartype="Pointer" Bytesize="8" OffsetHex="00000050" DisplayMethod="unsigned integer"/>
      <Element Offset="88" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000058" DisplayMethod="unsigned integer"/>
      <Element Offset="96" Vartype="Unicode String" Bytesize="13" OffsetHex="00000060" DisplayMethod="unsigned integer"/>
      <Element Offset="109" Vartype="Byte" Bytesize="1" OffsetHex="0000006D" DisplayMethod="unsigned integer"/>
      <Element Offset="110" Vartype="Unicode String" Bytesize="6" OffsetHex="0000006E" DisplayMethod="unsigned integer"/>
      <Element Offset="116" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000074" DisplayMethod="hexadecimal"/>
      <Element Offset="120" Vartype="4 Bytes" Bytesize="4" RLECount="15" OffsetHex="00000078" DisplayMethod="unsigned integer"/>
      <Element Offset="180" Vartype="Float" Bytesize="4" OffsetHex="000000B4" Description="距離" DisplayMethod="unsigned integer"/>
      <Element Offset="184" Vartype="4 Bytes" Bytesize="4" RLECount="19" OffsetHex="000000B8" DisplayMethod="unsigned integer"/>
      <Element Offset="260" Vartype="Float" Bytesize="4" OffsetHex="00000104" Description="x" DisplayMethod="unsigned integer"/>
      <Element Offset="264" Vartype="Float" Bytesize="4" OffsetHex="00000108" Description="y" DisplayMethod="unsigned integer"/>
      <Element Offset="268" Vartype="Float" Bytesize="4" OffsetHex="0000010C" Description="z" DisplayMethod="unsigned integer"/>
      <Element Offset="272" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000110" DisplayMethod="unsigned integer"/>
      <Element Offset="276" Vartype="Float" Bytesize="4" OffsetHex="00000114" Description="x" DisplayMethod="unsigned integer"/>
      <Element Offset="280" Vartype="Float" Bytesize="4" OffsetHex="00000118" Description="y" DisplayMethod="unsigned integer"/>
      <Element Offset="284" Vartype="Float" Bytesize="4" OffsetHex="0000011C" Description="z" DisplayMethod="unsigned integer"/>
      <Element Offset="288" Vartype="4 Bytes" Bytesize="4" RLECount="34" OffsetHex="00000120" DisplayMethod="unsigned integer"/>
      <Element Offset="424" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000001A8" DisplayMethod="hexadecimal"/>
      <Element Offset="432" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="000001B0" DisplayMethod="unsigned integer"/>
      <Element Offset="448" Vartype="4 Bytes" Bytesize="4" OffsetHex="000001C0" DisplayMethod="unsigned integer"/>
      <Element Offset="452" Vartype="4 Bytes" Bytesize="4" OffsetHex="000001C4" DisplayMethod="hexadecimal"/>
      <Element Offset="456" Vartype="Float" Bytesize="4" OffsetHex="000001C8" DisplayMethod="unsigned integer"/>
      <Element Offset="460" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="000001CC" DisplayMethod="unsigned integer"/>
      <Element Offset="472" Vartype="Pointer" Bytesize="8" OffsetHex="000001D8" DisplayMethod="unsigned integer"/>
      <Element Offset="480" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="000001E0" DisplayMethod="unsigned integer"/>
      <Element Offset="504" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000001F8" DisplayMethod="hexadecimal"/>
      <Element Offset="512" Vartype="4 Bytes" Bytesize="4" RLECount="34" OffsetHex="00000200" DisplayMethod="unsigned integer"/>
      <Element Offset="648" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000288" DisplayMethod="hexadecimal"/>
      <Element Offset="656" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000290" DisplayMethod="unsigned integer"/>
      <Element Offset="672" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="000002A0" DisplayMethod="unsigned integer"/>
      <Element Offset="684" Vartype="4 Bytes" Bytesize="4" OffsetHex="000002AC" DisplayMethod="hexadecimal"/>
      <Element Offset="688" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="000002B0" DisplayMethod="unsigned integer"/>
      <Element Offset="700" Vartype="4 Bytes" Bytesize="4" OffsetHex="000002BC" DisplayMethod="hexadecimal"/>
      <Element Offset="704" Vartype="4 Bytes" Bytesize="4" RLECount="5" OffsetHex="000002C0" DisplayMethod="unsigned integer"/>
      <Element Offset="724" Vartype="4 Bytes" Bytesize="4" OffsetHex="000002D4" DisplayMethod="hexadecimal"/>
      <Element Offset="728" Vartype="4 Bytes" Bytesize="4" RLECount="16" OffsetHex="000002D8" DisplayMethod="unsigned integer"/>
      <Element Offset="792" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000318" DisplayMethod="hexadecimal"/>
    </Elements>
  </Structure>
</Structures>